# Menus
bindd = SUPER, SPACE, Launch apps, exec, walker
bindd = SUPER CTRL, E, Emoji picker, exec, walker -m symbols
bindd = SUPER, ESCAPE, Power menu, exec, arch-power-menu
bindld = , XF86PowerOff, Power menu, exec, arch-power-menu
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, arch-toggle-waybar
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, arch-toggle-window-transparency
bindd = SUPER SHIFT, BACKSPACE, Toggle window gaps, exec, arch-toggle-window-gaps

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, arch-toggle-notification-silencing
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, arch-toggle-idle
bindd = SUPER CTRL, N, Toggle nightlight, exec, arch-toggle-nightlight
bindd = SUPER CTRL, Delete, Toggle laptop display, exec, arch-monitor-internal toggle

# Captures
bindd = , PRINT, Screenshot (region), exec, hyprshot -m region
bindd = ALT, PRINT, Screenshot (window), exec, hyprshot -m window
bindd = SHIFT, PRINT, Screenshot (output), exec, hyprshot -m output
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send -u low "$(date +"%A %H:%M  ·  %d %B %Y  ·  Week %V")"
bindd = SUPER CTRL ALT, B, Show battery remaining, exec, notify-send -u low "$(arch-battery-status)"

# Control panels (TUI, in floating terminal)
bindd = SUPER CTRL, A, Audio controls, exec, arch-floatterm arch-wiremix wiremix
bindd = SUPER CTRL, B, Bluetooth controls, exec, arch-floatterm arch-bluetui sh -c 'rfkill unblock bluetooth; exec bluetui'
bindd = SUPER CTRL, W, Wifi controls, exec, arch-floatterm arch-impala sh -c 'rfkill unblock wifi; exec impala'
bindd = SUPER CTRL, T, Activity, exec, arch-floatterm arch-btop btop

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, hyprlock
