# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = chromium
$cwd = arch-cmd-terminal-cwd

# Keybinds
bindd = SUPER, F1, Keybinds, exec, arch-floatterm arch-installer arch-keybinds

bindd = SUPER ALT, SPACE, Arch menu, exec, arch-menu

# Cleanup
unbind = SUPER, T
unbind = SUPER, B
unbind = SUPER, F
unbind = SUPER CTRL, A
unbind = SUPER, F11
unbind = SUPER, W

# Rebind fullscreen toggle
bindd = SUPER, F11, Fullscreen, fullscreen, 0

# Smart close: dismiss walker if visible, otherwise kill the focused window
bindd = SUPER, W, Close (or dismiss walker), exec, arch-killactive

# Default
bindd = SUPER, T, Terminal, exec, $terminal --dir="$($cwd)"
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER SHIFT, B, Browser (private), exec, $browser --incognito
bindd = SUPER, F, File manager, exec, uwsm app -- nautilus --new-window

# Apps
bindd = SUPER, M, Music, exec, arch-launch-app spotify
bindd = SUPER, N, Editor, exec, uwsm-app -- xdg-terminal-exec nvim
bindd = SUPER SHIFT, D, Docker, exec, uwsm-app -- xdg-terminal-exec lazydocker
bindd = SUPER, D, Discord, exec, discord-canary

# Proton stuff
bindd = SUPER, C, Calendar, exec, arch-launch-webapp proton-calendar "https://calendar.proton.me/u/0/"
bindd = SUPER, E, Email, exec, arch-launch-webapp proton-mail "https://mail.proton.me/u/0/inbox"

# AI stuff
bindd = SUPER , A, Claude, exec, arch-launch-webapp claude-ai "https://claude.ai/"
bindd = SUPER SHIFT, A, V0, exec, arch-launch-webapp v0-app "https://v0.app/"
bindd = SUPER CTRL, A, Gemini, exec, arch-launch-webapp gemini "https://gemini.google.com/app?hl=cs"

# Coms
bindd = SUPER, I, Instagram, exec, arch-launch-webapp instagram "https://www.instagram.com/"
bindd = SUPER SHIFT, I, WhatsApp, exec, arch-launch-webapp whatsapp "https://web.whatsapp.com/"
bindd = SUPER CTRL, I, Messenger, exec, arch-launch-webapp messenger "https://www.messenger.com/e2ee/t/28395601576750106/"
