# Floating windows
windowrule = float on, match:tag floating-window
windowrule = center on, match:tag floating-window
windowrule = size 875 600, match:tag floating-window

windowrule = tag +floating-window, match:class (org.codeberg.dnkl.foot|org.kde.okular|com.gabm.satty|org.kde.gwenview|mpv)
windowrule = tag +floating-window, match:class (xdg-desktop-portal-gtk|sublime_text|DesktopEditors), match:title ^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*)
windowrule = float on, match:class org.kde.kcalc

# No transparency on media windows
windowrule = tag -default-opacity, match:class ^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|org.kde.gwenview)$
windowrule = opacity 1 1, match:class ^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|org.kde.gwenview)$

# Popped window rounding
windowrule = rounding 8, match:tag pop

# Prevent idle while open
windowrule = idle_inhibit always, match:tag noidle
